'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Sparkles, X, Send, PanelRightClose, PanelRightOpen, Bot } from 'lucide-react';

interface CopilotMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
}

const SUGGESTIONS = [
  'Summarize today\'s fraud.',
  'Show risky MSMEs.',
  'Explain this recommendation.',
  'Open Digital Twin.',
  'Compare two branches.',
  'Show customers needing attention.',
];

function assistantReplyFor(prompt: string): string {
  const p = prompt.toLowerCase();
  if (p.includes('fraud')) {
    return 'Today: 3 high-severity fraud alerts flagged across Mumbai and Delhi clusters, mostly velocity anomalies on card-not-present transactions. Risk Intelligence recommends a manual review queue escalation.';
  }
  if (p.includes('msme')) {
    return 'MSME Intelligence surfaced 5 accounts trending toward elevated risk, primarily due to declining cash-flow coverage ratios. Ahmedabad CG Road cluster shows the highest concentration.';
  }
  if (p.includes('recommendation')) {
    return 'This recommendation was generated by the Decision Engine\'s Risk Reasoner, combining exposure scoring, portfolio concentration, and recent alert velocity into a single confidence-ranked action.';
  }
  if (p.includes('twin')) {
    return 'Opening the requested Digital Twin workspace — this module simulates a live operational mirror of the selected entity for scenario testing.';
  }
  if (p.includes('compare') && p.includes('branch')) {
    return 'Comparing branches: Mumbai BKC HQ leads on portfolio health and NPS, while Delhi Connaught Place shows stronger MSME origination velocity this quarter.';
  }
  if (p.includes('customer')) {
    return 'Customer Intelligence flags 12 accounts needing attention this week, primarily driven by service SLA breaches and dormant high-value relationships.';
  }
  return 'Understood. I\'m pulling context from the Enterprise Event Bus, Memory Engine, and relevant Intelligence workspaces to help with that — this is a demo response grounded in the current mock dataset.';
}

export const AICopilot: React.FC = () => {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<CopilotMessage[]>([
    {
      id: 'welcome',
      role: 'assistant',
      text: 'Hi, I\'m the CORTEX Copilot. Ask me about fraud signals, MSME risk, branch comparisons, or any workspace on the platform.',
    },
  ]);
  const scrollRef = useRef<HTMLDivElement>(null);
  const idCounter = useRef(0);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages, open]);

  const send = (text: string) => {
    const trimmed = text.trim();
    if (!trimmed) return;
    const userMsg: CopilotMessage = { id: `msg-${++idCounter.current}`, role: 'user', text: trimmed };
    setMessages((m) => [...m, userMsg]);
    setInput('');
    setTimeout(() => {
      setMessages((m) => [...m, { id: `msg-${++idCounter.current}`, role: 'assistant', text: assistantReplyFor(trimmed) }]);
    }, 500);
  };

  if (!open) {
    return (
      <button
        onClick={() => setOpen(true)}
        className="fixed right-5 bottom-6 z-40 w-11 h-11 rounded-full bg-emerald-700 hover:bg-emerald-600 text-white flex items-center justify-center shadow-lg shadow-emerald-950/50 transition-colors"
        title="Open AI Copilot"
      >
        <Sparkles size={17} />
      </button>
    );
  }

  return (
    <aside className="w-80 shrink-0 h-full bg-zinc-950 border-l border-zinc-900 flex flex-col font-mono animate-cortex-fade-in">
      <div className="h-14 border-b border-zinc-900 flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded bg-emerald-950/40 border border-emerald-900 flex items-center justify-center">
            <Bot size={13} className="text-emerald-500" />
          </div>
          <div>
            <div className="text-xs text-zinc-200 font-semibold leading-none">CORTEX Copilot</div>
            <div className="text-[9px] text-zinc-600 leading-none mt-1">AI Reasoning Assistant</div>
          </div>
        </div>
        <button onClick={() => setOpen(false)} className="text-zinc-500 hover:text-zinc-300 p-1">
          <PanelRightClose size={14} />
        </button>
      </div>

      <div ref={scrollRef} className="flex-1 overflow-y-auto scrollbar-thin px-4 py-4 space-y-3">
        {messages.map((m) => (
          <div
            key={m.id}
            className={`text-xs leading-relaxed rounded-lg px-3 py-2 max-w-[92%] ${
              m.role === 'user'
                ? 'bg-emerald-950/30 border border-emerald-900/50 text-emerald-100 ml-auto'
                : 'bg-zinc-900 border border-zinc-800 text-zinc-300'
            }`}
          >
            {m.text}
          </div>
        ))}
      </div>

      <div className="px-4 pb-2 flex flex-wrap gap-1.5">
        {SUGGESTIONS.slice(0, 3).map((s) => (
          <button
            key={s}
            onClick={() => send(s)}
            className="text-[10px] text-zinc-400 border border-zinc-800 hover:border-emerald-800 hover:text-emerald-400 rounded-full px-2.5 py-1 transition-colors"
          >
            {s}
          </button>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          send(input);
        }}
        className="border-t border-zinc-900 p-3 flex items-center gap-2 shrink-0"
      >
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask CORTEX..."
          className="flex-1 bg-zinc-900 border border-zinc-800 focus:border-emerald-800 rounded-lg px-3 py-2 text-xs text-zinc-200 placeholder-zinc-600 outline-none"
        />
        <button
          type="submit"
          className="w-8 h-8 shrink-0 rounded-lg bg-emerald-700 hover:bg-emerald-600 text-white flex items-center justify-center transition-colors"
        >
          <Send size={13} />
        </button>
      </form>
    </aside>
  );
};

export const AICopilotToggleIcon = PanelRightOpen;
export const AICopilotCloseIcon = X;

export default AICopilot;