import { AgentPluginMetadata } from '@/types';

export const AGENT_REGISTRY: AgentPluginMetadata[] = [
  {
    id: 'wealth-advisor',
    name: 'Wealth Advisor',
    description: 'Optimizes portfolio allocations and generates personalized investment proposals based on HNI customer risk profiles.',
    status: 'IDLE',
    capabilities: ['PortfolioOptimisation', 'RecommendationGeneration'],
    supportedEntities: ['Customer', 'Investment'],
    requiredServices: ['CustomerService', 'RecommendationService', 'MemoryEngine'],
    supportedEvents: ['TransactionCreated', 'RecommendationGenerated'],
    permissions: ['read:all'],
    futureTools: ['portfolioOptimizerTool', 'marketFeedReader', 'assetAllocator'],
    version: '1.0.0'
  },
  {
    id: 'lending-advisor',
    name: 'Lending Advisor',
    description: 'Evaluates retail loan applications, analyzes debt-service capability, and structures credit terms.',
    status: 'IDLE',
    capabilities: ['CreditAssessment', 'RecommendationGeneration'],
    supportedEntities: ['Customer', 'Loan'],
    requiredServices: ['CustomerService', 'RecommendationService', 'DecisionEngineService'],
    supportedEvents: ['LoanRequested', 'LoanApproved'],
    permissions: ['read:customer', 'read:loan', 'evaluate:decision'],
    futureTools: ['bureauScorer', 'ratioAnalyzer', 'repaymentScheduler'],
    version: '1.0.0'
  },
  {
    id: 'msme-analyst',
    name: 'MSME Analyst',
    description: 'Analyzes GST returns, banking cash-flow histories, and supply-chain dependencies to assess MSME credit risk.',
    status: 'IDLE',
    capabilities: ['CashFlowForecasting', 'CreditAssessment', 'BehaviourAnalysis'],
    supportedEntities: ['MSME', 'Loan'],
    requiredServices: ['MSMEAnalysisService', 'KnowledgeGraphService', 'IntegrationLayer'],
    supportedEvents: ['MSMEUpdated', 'LoanRequested'],
    permissions: ['read:msme', 'read:loan'],
    futureTools: ['gstExtractor', 'bankStatementParser', 'supplierNetworkAnalyzer'],
    version: '1.0.0'
  },
  {
    id: 'fraud-guardian',
    name: 'Fraud Guardian',
    description: 'Monitors real-time transactions and flag anomalies using rule-based filters and predictive graph path tracing.',
    status: 'IDLE',
    capabilities: ['FraudDetection', 'BehaviourAnalysis'],
    supportedEntities: ['Transaction', 'FraudCase'],
    requiredServices: ['FraudService', 'EventBus', 'KnowledgeGraphService'],
    supportedEvents: ['TransactionCreated', 'FraudAlertGenerated'],
    permissions: ['read:risk', 'read:all'],
    futureTools: ['anomalyDetector', 'blacklistChecker', 'transactionBlocker'],
    version: '1.0.0'
  },
  {
    id: 'compliance-officer',
    name: 'Compliance Officer',
    description: 'Validates KYC, checks PAN/Aadhaar databases via integration, and audits customer onboarding compliance.',
    status: 'IDLE',
    capabilities: ['DocumentAnalysis'],
    supportedEntities: ['Customer', 'Document'],
    requiredServices: ['DocumentIntelligence', 'IntegrationLayer', 'WorkflowEngine'],
    supportedEvents: ['DocumentProcessed', 'CustomerUpdated'],
    permissions: ['read:all', 'manage:workflows'],
    futureTools: ['panValidator', 'ckycSearcher', 'blacklistScreener'],
    version: '1.0.0'
  },
  {
    id: 'risk-analyst',
    name: 'Risk Analyst',
    description: 'Aggregates loan defaults, liquidity levels, and simulates systemic economic shocks on bank portfolios.',
    status: 'IDLE',
    capabilities: ['RiskScoring', 'SimulationExecution'],
    supportedEntities: ['Branch', 'RiskAssessment', 'Simulation'],
    requiredServices: ['RiskService', 'SimulationService', 'MemoryEngine'],
    supportedEvents: ['SimulationCompleted', 'DigitalTwinUpdated'],
    permissions: ['read:risk', 'trigger:simulation'],
    futureTools: ['stressTester', 'varCalculator', 'correlationEngine'],
    version: '1.0.0'
  },
  {
    id: 'executive-copilot',
    name: 'Executive Copilot',
    description: 'Synthesizes insights, explains decision rationales, and alerts executives to high-impact credit or operational risks.',
    status: 'IDLE',
    capabilities: ['RecommendationGeneration'],
    supportedEntities: ['Branch', 'Customer', 'MSME', 'Loan'],
    requiredServices: ['DecisionEngineService', 'ExplainabilityEngine', 'MemoryEngine'],
    supportedEvents: ['DecisionCompleted', 'FraudAlertGenerated', 'LoanApproved'],
    permissions: ['read:all', 'evaluate:decision'],
    futureTools: ['executiveSummaryGenerator', 'explainabilityAuditor', 'insightBroadcaster'],
    version: '1.0.0'
  },
  {
    id: 'relationship-manager',
    name: 'Relationship Manager',
    description: 'Assists human RMs by tracking customer health indicators, mapping ownership graphs, and flagging upsell alerts.',
    status: 'IDLE',
    capabilities: ['CustomerSegmentation', 'BehaviourAnalysis'],
    supportedEntities: ['Customer', 'MSME'],
    requiredServices: ['CustomerService', 'KnowledgeGraphService', 'DigitalTwinService'],
    supportedEvents: ['CustomerUpdated', 'MSMEUpdated'],
    permissions: ['read:customer', 'read:msme'],
    futureTools: ['rmDashboardPopulator', 'entityConnector', 'alertGenerator'],
    version: '1.0.0'
  },
  {
    id: 'customer-success-agent',
    name: 'Customer Success Agent',
    description: 'Answers customer account queries and initiates onboarding workflows autonomously.',
    status: 'IDLE',
    capabilities: ['BehaviourAnalysis'],
    supportedEntities: ['Customer', 'Account'],
    requiredServices: ['CustomerService', 'WorkflowEngine', 'MemoryEngine'],
    supportedEvents: ['CustomerUpdated'],
    permissions: ['read:customer', 'write:customer'],
    futureTools: ['supportTicketFiler', 'accountStatusChecker'],
    version: '1.0.0'
  },
  {
    id: 'document-intelligence-agent',
    name: 'Document Intelligence Agent',
    description: 'Extracts structural tabular financial items, dates, and names from complex multi-page PDF documents.',
    status: 'IDLE',
    capabilities: ['DocumentAnalysis'],
    supportedEntities: ['Document'],
    requiredServices: ['DocumentIntelligence'],
    supportedEvents: ['DocumentProcessed'],
    permissions: ['read:all'],
    futureTools: ['pdfParser', 'ocrScanner', 'signatureVerifier'],
    version: '1.0.0'
  }
];
