import { WorkspaceConfig } from '@/types';

export const WORKSPACE_REGISTRY: WorkspaceConfig[] = [
  {
    id: 'overview',
    route: '/overview',
    title: 'Overview',
    description: 'System-wide operational overview and cognitive health index.',
    icon: 'Activity',
    permissions: ['read:all'],
    requiredServices: ['DecisionEngineService', 'AgentOrchestratorService'],
    featureFlags: [],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'customer-intelligence',
    route: '/customer-intelligence',
    title: 'Customer Intelligence',
    description: 'Advanced behavioral analytics, lifecycle signals, and value modeling.',
    icon: 'Users',
    permissions: ['read:customer'],
    requiredServices: ['CustomerService', 'DigitalTwinService'],
    featureFlags: [],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'digital-twins',
    route: '/digital-twins',
    title: 'Digital Twins',
    description: 'Real-time simulated replicas of customers, portfolios, and branch units.',
    icon: 'Binary',
    permissions: ['read:all'],
    requiredServices: ['DigitalTwinService', 'KnowledgeGraphService'],
    featureFlags: ['enable-digital-twins'],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'agent-center',
    route: '/agent-center',
    title: 'AI Agent Center',
    description: 'Orchestration dashboard for autonomous agent plugins and tooling.',
    icon: 'Cpu',
    permissions: ['manage:agents'],
    requiredServices: ['AgentOrchestratorService'],
    featureFlags: [],
    sidebarGroup: 'management',
    isEnabled: true
  },
  {
    id: 'knowledge-graph',
    route: '/knowledge-graph',
    title: 'Knowledge Graph',
    description: 'Interactive semantic graph mapping corporate ownership, guarantors, and transactions.',
    icon: 'Network',
    permissions: ['read:all'],
    requiredServices: ['KnowledgeGraphService'],
    featureFlags: [],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'decision-intelligence',
    route: '/decision-intelligence',
    title: 'Decision Intelligence',
    description: 'Audit traces, explanation paths, and manual overrides for CORTEX DE.',
    icon: 'Brain',
    permissions: ['evaluate:decision'],
    requiredServices: ['DecisionEngineService', 'ExplainabilityEngine'],
    featureFlags: [],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'simulation-engine',
    route: '/simulation-engine',
    title: 'Simulation Engine',
    description: 'Macro-economic stress testing and credit portfolio shock simulations.',
    icon: 'TrendingUp',
    permissions: ['trigger:simulation'],
    requiredServices: ['SimulationService'],
    featureFlags: [],
    sidebarGroup: 'intelligence',
    isEnabled: true
  },
  {
    id: 'fraud',
    route: '/fraud',
    title: 'Fraud Intelligence',
    description: 'Real-time transaction anomaly analysis and AML monitoring.',
    icon: 'ShieldAlert',
    permissions: ['read:risk'],
    requiredServices: ['FraudService', 'EventBus'],
    featureFlags: [],
    sidebarGroup: 'operations',
    isEnabled: true
  },
  {
    id: 'risk',
    route: '/risk',
    title: 'Risk Intelligence',
    description: 'Credit, liquidity, and operational risk metrics aggregate view.',
    icon: 'AlertTriangle',
    permissions: ['read:risk'],
    requiredServices: ['RiskService'],
    featureFlags: [],
    sidebarGroup: 'operations',
    isEnabled: true
  },
  {
    id: 'lending',
    route: '/lending',
    title: 'Lending Intelligence',
    description: 'Retail & commercial loan underwriting decision assistance.',
    icon: 'Briefcase',
    permissions: ['read:loan'],
    requiredServices: ['RecommendationService', 'CustomerService'],
    featureFlags: [],
    sidebarGroup: 'operations',
    isEnabled: true
  },
  {
    id: 'wealth',
    route: '/wealth',
    title: 'Wealth Intelligence',
    description: 'Portfolio allocation optimization suggestions for HNI customers.',
    icon: 'Coins',
    permissions: ['read:all'],
    requiredServices: ['RecommendationService'],
    featureFlags: [],
    sidebarGroup: 'operations',
    isEnabled: true
  },
  {
    id: 'msme',
    route: '/msme',
    title: 'MSME Intelligence',
    description: 'Supply chain health, GST data flows, and cash-flow credit assessment.',
    icon: 'Store',
    permissions: ['read:msme'],
    requiredServices: ['MSMEAnalysisService'],
    featureFlags: [],
    sidebarGroup: 'operations',
    isEnabled: true
  },
  {
    id: 'compliance',
    route: '/compliance',
    title: 'Compliance',
    description: 'Automated audit checklist tracking, CKYC records, and regulatory checks.',
    icon: 'FileCheck',
    permissions: ['read:all'],
    requiredServices: ['WorkflowEngine'],
    featureFlags: [],
    sidebarGroup: 'management',
    isEnabled: true
  },
  {
    id: 'executive',
    route: '/executive',
    title: 'Executive Dashboard',
    description: 'High-level strategic insights for regional managers and executive board.',
    icon: 'LayoutDashboard',
    permissions: ['read:all'],
    requiredServices: ['DecisionEngineService', 'KnowledgeGraphService'],
    featureFlags: [],
    sidebarGroup: 'management',
    isEnabled: true
  },
  {
    id: 'settings',
    route: '/settings',
    title: 'Settings',
    description: 'RBAC user simulator, theme toggles, and feature flag management.',
    icon: 'Settings',
    permissions: ['read:all'],
    requiredServices: [],
    featureFlags: [],
    sidebarGroup: 'system',
    isEnabled: true
  }
];
